more debug

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -29,12 +29,13 @@ jobs:
       - name: Clone swift-format
         shell: sh
         run: |
+          cd ..
           git clone --depth 1 https://github.com/swiftlang/swift-format.git
 
       - name: Cache swift-format build
         uses: actions/cache@v4
         with:
-          path: swift-format/.build
+          path: ../swift-format/.build
           key: ${{ runner.os }}-swift-format-build-${{ hashFiles('swift-format/Package.swift', 'swift-format/Package.resolved') }}-${{ steps.setup-swift.outputs.swift-version }}
           restore-keys: |
             ${{ runner.os }}-swift-format-build-
@@ -42,20 +43,21 @@ jobs:
       - name: Build swift-format
         shell: sh
         run: |
-          cd swift-format
+          cd ../swift-format
           swift build -c release
 
       - name: Link swift-format to /usr/local/bin
         shell: sh
         run: |
+          cd swift-format
           ln -s "$(swift build --show-bin-path -c release)/swift-format" /usr/local/bin/swift-format
      
       - name: Run style checks
         shell: sh
         run: |
           pwd
-          ls -l
-          pre-commit run --all || (echo "Style checks failed, please install pre-commit and run pre-commit run --all and push the change"; echo ""; git --no-pager diff; exit 1)
+          ls -la
+          # pre-commit run --all || (echo "Style checks failed, please install pre-commit and run pre-commit run --all and push the change"; echo ""; git --no-pager diff; exit 1)
       
 
   mac_build_and_test:
